### ISSUE TITLE
some wrong

### ISSUE THREAD

**Issue by zhefox** [singleghost2/IDA-Notepad-plus#1]
C:\Program Files\IDA Professional 9.0\plugins\ida_notepad_plus.py: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\Program Files\IDA Professional 9.0\python\3\ida_idaapi.py", line 573, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Professional 9.0/plugins/ida_notepad_plus.py", line 17, in <module>
    API_MD = os.path.join(IDB_DIR, "Notes-" + idaapi.get_root_filename())
TypeError: can only concatenate str (not "NoneType") to str

**Comment by zhefox** [comment]
看起来IDB_DIR = os.path.dirname(idc.get_idb_path())我打印了一下，此处获取的IDB_DIR值是空的？但是奇怪的是，文件夹是有创建出来的
C:\Users\user\Desktop\xx\Notes-xxx.sys

**Comment by zhefox** [comment]
get_root_filename:None
get_idb_path:
C:\Program Files\IDA Professional 9.0\plugins\ida_notepad_plus.py: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\Program Files\IDA Professional 9.0\python\3\ida_idaapi.py", line 573, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Professional 9.0/plugins/ida_notepad_plus.py", line 19, in <module>
    API_MD = os.path.join(IDB_DIR, "Notes-" + idaapi.get_root_filename())
TypeError: can only concatenate str (not "NoneType") to str

**Comment by zhefox** [comment]
#2 fixed
